"""
agents/summary_agent.py
========================
Agent 3 — Clinical Summary Agent.

Synthesizes all pipeline outputs (prediction + XAI + validation) into
a professional, structured clinical report formatted for physician review.

LLM Backend: Qwen/Qwen2.5-72B-Instruct via HuggingFace Inference API.
"""

import os
import logging
from typing import List, Dict, Optional
from langchain_core.prompts import PromptTemplate

logger = logging.getLogger(__name__)


class SummaryAgent:
    """
    Expert Medical Report Writer Agent.

    System Role:
        "You are an expert medical report writer. Synthesize the model prediction,
         XAI explanation, and validation findings into a professional, structured
         clinical report suitable for a physician."

    Input:  Agent 1 output + Agent 2 output + raw prediction metadata.
    Output: Structured medical report with all required sections.
    """

    def __init__(
        self,
        model_name: str = "Qwen/Qwen2.5-72B-Instruct",
        hf_mode: str = "api",
        max_tokens: int = 900,  # Summary needs more tokens for full report
    ):
        """
        Args:
            model_name: HuggingFace model repository.
            hf_mode:    'api' = HF Inference API | 'local' = local pipeline.
            max_tokens: Max generation tokens (increase for longer reports).
        """
        logger.info(f"Initializing Summary Agent: {model_name} (mode={hf_mode})")
        self.llm = self._load_llm(model_name, hf_mode, max_tokens)

        # Medical report generation prompt
        self.prompt = PromptTemplate(
            input_variables=[
                "patient_synopsis", "image_modality", "body_region",
                "diagnosis", "confidence", "dominant_modality",
                "clinical_reasoning", "validation_report",
            ],
            template="""You are a senior clinical AI medical report writer.

Synthesize the following information into a structured, professional radiology-style AI report.

=== INPUT DATA ===
PATIENT SYNOPSIS: {patient_synopsis}
IMAGING: {image_modality} — {body_region}
AI DIAGNOSIS: {diagnosis} | CONFIDENCE: {confidence}% | PRIMARY EVIDENCE: {dominant_modality} branch
XAI EXPLANATION: {clinical_reasoning}
HISTORICAL VALIDATION: {validation_report}

=== REQUIRED OUTPUT FORMAT (Markdown) ===
Generate the report with EXACTLY these sections, in this order:

## 🏥 Patient Summary
[Brief 2-3 sentence clinical overview based on the synopsis]

## 🔬 Predicted Diagnosis & Confidence
**Diagnosis:** {diagnosis}
**Model Confidence:** {confidence}%
**Primary Evidence Source:** {dominant_modality} modality
[1 sentence on confidence interpretation]

## 🧠 Clinical Reasoning (XAI)
[3-4 sentence synthesis of radiological and textual findings into clinical logic]

## 📁 Historical Case Validation
[2-3 sentence summary of validation against retrieved cases]

## ⚠️ Caveats & Limitations
[2 sentences on what this AI report can and cannot do — appropriate medical AI caveats]

## 📋 Recommended Next Steps
1. [Step 1]
2. [Step 2]
3. [Step 3]

---
*Report generated by Multimodal Clinical AI Pipeline (Trial_2) — FOR PHYSICIAN REVIEW ONLY*

CLINICAL REPORT:""",
        )

    def _load_llm(self, model_name: str, hf_mode: str, max_tokens: int):
        """Load the LLM backend."""
        try:
            if hf_mode == "api":
                from huggingface_hub import InferenceClient

                class HFAPIWrapper:
                    def __init__(self, model: str, max_tok: int):
                        token = os.getenv("HUGGINGFACEHUB_API_TOKEN", "")
                        self.client  = InferenceClient(api_key=token)
                        self.model   = model
                        self.max_tok = max_tok

                    def invoke(self, prompt: str) -> str:
                        try:
                            response = self.client.chat_completion(
                                model=self.model,
                                messages=[
                                    {"role": "system", "content": "You are a clinical AI medical report specialist."},
                                    {"role": "user",   "content": prompt},
                                ],
                                max_tokens=self.max_tok,
                                temperature=0.2,  # Slightly higher for narrative fluency
                            )
                            return response.choices[0].message.content
                        except Exception as e:
                            logger.error(f"HF API call failed: {e}")
                            return f"[Summary Report Error: {e}]"

                return HFAPIWrapper(model_name, max_tokens)
            elif hf_mode == "local":
                from langchain_huggingface import HuggingFacePipeline
                return HuggingFacePipeline.from_model_id(
                    model_id=model_name,
                    task="text-generation",
                    pipeline_kwargs={"max_new_tokens": max_tokens},
                )
        except Exception as e:
            logger.warning(f"Summary LLM backend failed: {e}. Using fallback.")
            return None

    def generate_report(
        self,
        patient_synopsis: str,
        diagnosis: str,
        confidence: float,
        clinical_reasoning: str,
        validation_report: str,
        image_modality: str = "CT",
        body_region: str = "chest",
        dominant_modality: str = "image",
    ) -> str:
        """
        Generate the final structured clinical report.

        Args:
            patient_synopsis:   Brief description of the patient case.
            diagnosis:          Predicted disease class name.
            confidence:         Model confidence [0,1].
            clinical_reasoning: Output from Explanation Agent (Agent 1).
            validation_report:  Output from Validation Agent (Agent 2).
            image_modality:     CT or MR.
            body_region:        Anatomical region.
            dominant_modality:  'image' or 'text' (from Integrated Gradients).
        Returns:
            Structured Markdown clinical report (string).
        """
        if self.llm is None:
            return self._fallback_report(
                patient_synopsis, diagnosis, confidence,
                clinical_reasoning, validation_report,
            )

        prompt_text = self.prompt.format(
            patient_synopsis=patient_synopsis[:500],  # Truncate for token budget
            image_modality=image_modality,
            body_region=body_region,
            diagnosis=diagnosis,
            confidence=round(confidence * 100, 1),
            dominant_modality=dominant_modality,
            clinical_reasoning=clinical_reasoning[:400],
            validation_report=validation_report[:400],
        )

        logger.info("Summary Agent generating final clinical report...")
        return self.llm.invoke(prompt_text)

    def _fallback_report(
        self,
        synopsis: str,
        diagnosis: str,
        confidence: float,
        reasoning: str,
        validation: str,
    ) -> str:
        """Rule-based fallback report when LLM is unavailable."""
        return f"""## 🏥 Patient Summary
{synopsis[:200]}

## 🔬 Predicted Diagnosis & Confidence
**Diagnosis:** {diagnosis}
**Model Confidence:** {confidence:.1%}

## 🧠 Clinical Reasoning (XAI)
{reasoning}

## 📁 Historical Case Validation
{validation}

## ⚠️ Caveats & Limitations
This report was generated by an AI system for decision support only.
All findings must be reviewed and confirmed by a qualified physician.

## 📋 Recommended Next Steps
1. Review imaging with radiologist.
2. Correlate with full clinical history.
3. Order confirmatory diagnostic tests as indicated.

---
*Report generated by Multimodal Clinical AI Pipeline (Trial_2) — FOR PHYSICIAN REVIEW ONLY*
*[Note: LLM unavailable — structured fallback report used]*"""
